### ISSUE TITLE
Run code For Android

### ISSUE THREAD

**Issue by hilmanfitriana19** [bookbot-kids/speech-recognizer-bahasa-indonesian#2]
hello, I'm trying to run this source code to install using my cellphone device. After following the installation procedure, the application has been running successfully, but when it is about to run its features by pressing the 'Start listening' button, the application will force close. The error that appears is :
    
    java.io.FileNotFoundException: model-id-id/uuid.

If we refer to the error that appears, the `model-id-id/uuid` file is not found. I thought the file was accessible in `android\models\src\main\assets\model-id-id\uuid`, but after the application runs the file path changes to `/storage/emulated/0/android/data/com.bookbot.speech_recognizer/files/model-id-id`. How to resolve the error? 

Thanks you

**Comment by nmfisher** [comment]
@hilmanfitriana19 can you please advise which device you're running this on (physical device? emulator?), which Android version, and how you're running it (VS Code Flutter plugin? Command line `flutter run`? Android Studio? etc)

Also it would help if you provide the output of:
```
flutter doctor -v
```

and also try
```
git reset --hard
git pull
flutter clean
flutter packages upgrade
```

So far we haven't been able to reproduce this on various Android devices/emulators/APIs so this will help us narrow down where the issue is.

**Comment by ductranminh** [comment]
@hilmanfitriana19 sorry for late response. We fixed the issue, so you can try it again.
